sudo: required
services:
  - docker

before_install:
  - docker build -t jayat19/frontend -f Dockerfile.dev .

script:
  - docker run jayat19/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-337755695599"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"